#ifndef NOTIFYSERVICE_GLOBAL_H
#define NOTIFYSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMLNOTYFYSERICE_LIBRARY)
#  define NOTIFYSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NOTIFYSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif


#endif // NOTIFYSERVICE_GLOBAL_H
